# -*- coding: utf-8 -*-
"""
Created on Mon Aug  1 23:52:03 2022

@author: fariz
"""
[theme]

primaryColor="#6eb52f"
backgroundColor="#f0f0f5"
secondaryBackgroundColor="#e0e0ef"
textColor="#262730"
font="sans serif"
